### ISSUE TITLE
Footer keep staying up

### ISSUE THREAD

**Issue by iyilm4z** [mledour/angular-admin-lte#37]
First of all thanks for this masterpiece implementation of lte! It's definitely best one so far.
Well.. you know we are all developers and we often use use browser's dev tool. 
Sometimes i'm facing the issue in the picture and i don't have any pattern how and when it happens. 
I press F12 to show dev tool and again press F12 to hide it but footer keep staying up like in the picture.

Thanks in advance.

![issue](https://user-images.githubusercontent.com/9105939/53735147-1c762780-3e97-11e9-8952-3f310cdd9ed7.JPG)

**Comment by gcanu** [comment]
I have exactly the same problem and have found the origin of the problem :

The calculation of the height of the content wrapper is done when router triggers navigationEnd event. Unfortunately this event has been triggered before adminLTE's content component suscribed to router event ! This is probably due to the suscribing at isCustomLayout (layout service)...

To be continued !

**Comment by iyilm4z** [comment]
@gcanu fixed thanks a lot! i hope @mledour will do something about this :)

**Comment by mledour** [comment]
Hi,

fixed in the latest release ;)

**Comment by iyilm4z** [comment]
@mledour thanks man! :)

**Comment by iyilm4z** [comment]
Hi @mledour, unfortunately this issue still existing. as i remember i tested it after your commit and it was working. but yesterday i faced with this issue again.  could you please test it with an empty home page with the new code as i did below. thanks.

<img width="952" alt="Capture" src="https://user-images.githubusercontent.com/9105939/60767191-e7841680-a0bc-11e9-8b8c-e2ef9218e922.PNG">
